### ISSUE TITLE
How do I make text Justified

### ISSUE THREAD

**Issue by Chetankumar-Akarte** [remoteportal/simple_rich_text#1]
Your package is awesome. I want to make Paragraph Justified. How I can do that?

**Comment by yauhenipakala** [comment]
No ways by default

you can do this by customizing widget:

- go to the end of the widget:
https://github.com/remoteportal/simple_rich_text/blob/b7484daadc607a43825eab6a5df1ca2f8473d80c/lib/simple_rich_text.dart#L265

- add `textAlign` to `RichText`:
```dart
return RichText(
  text: TextSpan(children: children),
  textAlign: TextAlign.justify,
);
```

**Comment by remoteportal** [comment]
Version 2.0.36 (2021-04-21)
