### ISSUE TITLE
[Bug][Android] Font size

### ISSUE THREAD

**Issue by yauhenipakala** [remoteportal/simple_rich_text#5]
simple_rich_text: 1.0.35

## Flutter bug:
https://github.com/flutter/flutter/issues/14675

## Solution:

Replace `RichText` to `Text.rich`:

https://github.com/remoteportal/simple_rich_text/blob/b7484daadc607a43825eab6a5df1ca2f8473d80c/lib/simple_rich_text.dart#L265

**Comment by remoteportal** [comment]
Fixed in 2.0.35.

THANK YOU!
