### ISSUE TITLE
Add the textScaleFactor parameter

### ISSUE THREAD

**Issue by timbotimbo** [remoteportal/simple_rich_text#6]
A `Text` widget scales the font based on the `textScaleFactor * fontSize`. 
If you never set this scale, it uses the value from the context, which is usually determined by the accessibility settings in android. 

`RichText` doesn't seem to do use the context `textScaleFactor` by default, which makes **simple_rich_text** ignore it too.
So on some phones the rich text is a different size from any other text widgets.

Using a mediaquery  `RichText` follows the behavior of normal `Text` widgets.
```
RichText(
    text: ,
    textScaleFactor: MediaQuery.of(context).textScaleFactor,
);
```

Can you add this parameter to the **simple_rich_text** constructor, and pass that to `RichText`?

Here is how you can manually set the global textScaleFactor in main to do some testing.

```
return new MaterialApp(
      //set global text scale factor in builder
      builder: (BuildContext context, Widget child) {
        final MediaQueryData data = MediaQuery.of(context);
        return MediaQuery(
          data: data.copyWith(textScaleFactor: 1),
          child: child,
        );
      },
```

**Comment by remoteportal** [comment]
Thank you for the thorough explanation!

**Comment by remoteportal** [comment]
Version 2.0.45 (2021-04-22)

**Comment by timbotimbo** [comment]
Thanks for fixing it so quickly. 

The current fix is fine for my use case, so you don't need to change anything. But for more flexibility in the future you might want the textScaleFactor to be customizable like the overflow and maxLines.

Something like
`textScaleFactor: this.textScaleFactor ?? MediaQuery.of(context).textScaleFactor`

**Comment by remoteportal** [comment]
Thank you for your feedback!

**Comment by remoteportal** [comment]
I added it for completeness.
