### ISSUE TITLE
Can't add a / in a url

### ISSUE THREAD

**Issue by cekrozl1** [remoteportal/simple_rich_text#8]
Hi ! 
I'm using this great package of yours but I can't find a way to add a '/' in a URL.
The closest I came was by using \\/ which displays / but breaks the URL logic:

`"_{http:www.developer.android.com\\/platform\\/technology\\/app-bundle;color:blue}AAB_"`
same result with 
`r'_{http:www.developer.android.com\/platform\/technology\/app-bundle;color:blue}AAB_',`

Is there something else I should try?

**Comment by cekrozl1** [comment]
Hi again !
I added `chars: r"(?=(?![^{]*}))[*~/_\\]",`
as input parameter and, well, it works fine now ! 
Thanks !!
:)

**Comment by bouziane** [comment]
Hello cekrozl1
 I have the same problem like you. 
Can you give more details of workaround please?

For my situation i use this 
_{http:bibliotheques.paris.fr\/Default\/sinscrire-en-bibliotheque.aspx;color:blue} by this link_

Best Regards
